### ISSUE TITLE
SQL db

### ISSUE THREAD

**Issue by bbday** [vecode/GW2Trader#1]
I'm looking for your work.

I have a issue after compiled (VS 2013), I have only 7 items in list (cached?), i think I missed SQL db.
Also if i try to see MainWindow.xaml (GW2Trader) i have a error about: "Error occured while establishing a connection to SQL server".

"<Window.Resources>
        <view:MainViewModel x:Key="MainViewModel"/>
</Window.Resources>"

**Comment by vecode** [comment]
Hi bbday,

thank you for your interest in my work. Do you only see 7 items after starting the application or is that after using the (not fully implemented) search? In my last commit I added a paginated observablecollection class with a default pagesize of 10. So seeing only 7 items is definitely strange. 
I will probably remove or change this class soon as I am not fully satisfied with its functionality yet. 

I'm getting the error message regarding the connection to SQL server too and am currently not sure whether this happens because of an error in my code or because the xaml designer is just not able to connect to a db (maybe to improve performance?). This error does not limit the functionality in the actual application though.
